# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-27 15:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blinkers', '0002_newhope_fetch'),
    ]

    operations = [
        migrations.CreateModel(
            name='FarFarAway',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last', models.IntegerField(default=12)),
                ('hope', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blinkers.NewHope')),
            ],
        ),
    ]
