# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-27 15:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('switches', '0002_auto_20161227_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farfaraway',
            name='last',
            field=models.IntegerField(default=12),
        ),
    ]
