# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-27 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blinkers', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            """
            --
            -- Add field fetch to newhope
            --
            ALTER TABLE "blinkers_newhope" ADD COLUMN ("fetch" integer NOT NULL); 
            """,
            reverse_sql="ALTER TABLE `blinkers_newhope` REMOVE COLUMN 'fetch';",
            state_operations=[
                migrations.AddField(
                    model_name='newhope',
                    name='fetch',
                    field=models.IntegerField(default=12),
                ),
            ]
        )
    ]
